on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Verilog source files with Verilator
        uses: librecores/ci-fusesoc-action@master
        with:
          command: 'run'
          core: 'chipsalliance.org:cores:SweRV_EL2'
          target: 'lint'
          tool: 'verilator'
